### ISSUE TITLE
Angle brackets stripped from templates

### ISSUE THREAD

**Issue by fpw** [tatuylonen/wiktextract#129]
Hi,

in recent versions, it seems that certain parameters are stripped from the head and inflection templates.

Example: https://kaikki.org/dictionary/Latin/meaning/f/fa/fabella.html#fabella-la-noun-BWIvysDn

The noun template is supposed to be `{{la-noun|fābella<1>}}`, but it's listed as `{{la-noun|fābella}}`. Passing parameters in angle brackets is quite common in the Latin Wiktionary and they used to be there a few months ago. 

It would be great if these parameters could be restored as I need the full template strings in my projects.

**Comment by tatuylonen** [comment]
Thanks for reporting this.  I just committed a fix.  I changed the cleaning of template arguments some weeks ago and the issue was probably introduced there.  Now if the content inside angle brackets starts with a digit it is not cleaned.  Do you think this is sufficient or are there some markers that are letters?  (I vaguely seem to remember having seen such markers and have some concern about whether the current fix is sufficient.)

The change should be reflected on https://kaikki.org tomorrow (hopefully - I've had some issues getting the update run getting stuck in recent days, but I think I fixed that problem earlier today).

**Comment by fpw** [comment]
Thanks for the quick reply! The JSON files on kaikki.org are really useful for my project as I'm building a Latin dictionary based on the information in the inflection template strings and this used to work perfectly in older versions.

The angle bracket parameters can contain arbitrary strings, here's an example where it doesn't start with a digit: https://en.wiktionary.org/wiki/Jesus#Latin (`{{la-ndecl|Jesus<irreg>}}`)

The parameters can even contain nested angle brackets to refer to other templates with their own parameters. It's basically the way how this and several other modules pass a 2nd level of parameters into the inflection engine.

I think there shouldn't be any assumptions on how the string between the `|` delimiters is constructed.

**Comment by fpw** [comment]
Sorry, hit the wrong button and didn't mean to close the ticket.

**Comment by fpw** [comment]
For reference, here are some of the more complex parameters:

HTML and Wiki tags in the parameter:
`{{head|la|numeral|feminine|[[IIda]]</b> ''or'' <b>[[IIda|II<sup>da</sup>]]|neuter|[[IIdum]]</b> ''or'' <b>[[IIdum|II<sup>dum</sup>]]|head2=II<sup>dus</sup>}}`

Parameter in the middle of the string:
`{{la-adj|īdem<irreg+.sufn>dem|pos=determiners}}`

Everything mixed:
`{{la-noun|humus<2.loc>|abl_sg=humō/humū|loc_pl=―|footnote=<i class=\"Latn mention\" lang=\"la\">humus</i> is one of a handful of common nouns that take the [[locative case]] (<i class=\"Latn mention\" lang=\"la\">[[humi#Latin|humī]]</i>); other such nouns include <i class=\"Latn mention\" lang=\"la\">[[domus#Latin|domus]]</i> and <i class=\"Latn mention\" lang=\"la\">[[rus#Latin|rūs]]</i>. Also, irregular ablative singular <i class=\"Latn mention\" lang=\"la\">[[humu#Latin|humū]]</i> once used by Varro.|g=f}}`

**Comment by fpw** [comment]
Can confirm that parameters starting with a letter are still missing now:
https://kaikki.org/dictionary/Latin/meaning/J/Je/Jesus.html#Jesus-la-name-ehHppphR

Inflection template shown as `{{la-ndecl|Jesus}}`
Should be `{{la-ndecl|Jesus<irreg>}}` (https://en.wiktionary.org/wiki/Jesus#Latin)

**Comment by tatuylonen** [comment]
Sorry about the delay in getting back to this.  I changed the code so that HTML tags are not stripped when cleaning template arguments.  I tried to test the cases you listed and both numeric and non-numeric parts in angle brackets are now kept.  However, I wasn't entirely sure of all your examples which word was in question (e.g., īdem does not seem to exist as a word in Wiktionary).

The changes should be reflected on https://kaikki.org within a couple of days.  Let me know if more is needed.

**Comment by fpw** [comment]
Thanks, I will check and report back!

Meanwhile, here's the page for īdem: https://en.wiktionary.org/wiki/idem#Latin

**Comment by fpw** [comment]
Looks great in the JSON now, thanks a lot!

In the HTML displayed on your site, the angle brackets are not converted to HTML, so the browser interprets them as HTML tags, making them invisible. Maybe the HTML generator should convert angle brackets to &lt; and &gt;, but this is only a cosmetic issue since the JSON is correct.

**Comment by tatuylonen** [comment]
I just fixed escaping in the website generation script.  Thanks for pointing it out.  Assuming my fix works (it's a bit tricky to test quickly) the change should be reflected on https://kaikki.org in a couple of days.

**Comment by fpw** [comment]
Everything related to this seems fixed now, thanks again!
