### ISSUE TITLE
Inflection Tables Missing from Certain Entries In French Wiktionary

### ISSUE THREAD

**Issue by ryellman** [tatuylonen/wiktextract#724]
Hi! I just wanted to start off by thanking you for this project. I have found it extremely helpful in my work.

One issue that I have noticed in the French language wiktionary dump is that some entries for verbs contain the inflection data from the conjugation tables that appear on the wiki pages while others do not. For example, the 'forms' key on 'avoir' contains the inflections for each of the conjugations found on the wiki page while the entry for 'être' does not have the forms key. 

I wonder if this is potentially due to the fact that the conjugation tables are generally on their own page in the French wiki versus contained in the page itself like in the English version of wiktionary.

**Comment by xxyzz** [comment]
This line https://github.com/tatuylonen/wiktextract/blob/ea57f1fdf125c52d3afdf1499670d8282282aace/src/wiktextract/extractor/fr/conjugation.py#L30

doesn't handle the "fr-conj" template in page "Conjugaison:français/être", I will take a closer look at this issue tomorrow.

**Comment by xxyzz** [comment]
#725 should fix this issue

**Comment by ryellman** [comment]
Thank you for addressing that issue so quickly. Do you believe this will also fix the issue causing reflexive verbs to be missing their conjugation tables?

If it would be helpful, I could provide you a frequency based list of the verbs that were missing conjugation tables in the JSON. It seemed that common verbs that had conjugation tables on wiktionary but not in their JSON were much more likely to be reflexive, whereas non-reflexive verbs were generally missing conjugation tables on wiktionary since they were rare/new verbs (like googletraduire).

**Comment by xxyzz** [comment]
The code only try to parse "Conjugaison" namespace pages if a page uses the ["conjugaison" template](https://fr.wiktionary.org/wiki/Mod%C3%A8le:conjugaison) which expands to a link to its conjugaison page.

If you find pages use the "conjugaison" template but their conjugaison page data are not extracted, please list some of these pages and I'll check them tomorrow.

**Comment by ryellman** [comment]
Thanks that makes sense. A couple examples of the ones that I noticed that didn't have the conjugations in the JSON but which had tables in their associated wiki pages were:

débloquer
blesser
s’inspirer
se disputer

**Comment by xxyzz** [comment]
All mentioned pages are fixed by #733

**Comment by ryellman** [comment]
Thanks, this is great. This reduced the total number of verb infinitive entries without inflection arrays from 4264 to 3153 (467 to 231 for reflexive verbs). A substantial number of these (probably the majority) are entries for wiktionary pages that are themselves missing associated conjugation tables. However, I found some that were still missing forms arrays despite having conjugation tables in wiktionary. For example:

se justifier
s’opacifier
philosophier
métrifier
repurifier

**Comment by xxyzz** [comment]
All of them use the [fr-conj-1-ier](https://fr.wiktionary.org/wiki/Mod%C3%A8le:fr-conj-1-ier) template and should be fixed by #739.

**Comment by ryellman** [comment]
Ah that makes sense - looking at it now I see that the vast majority of verbs that still did not have forms arrays ended in -ier. Removing those verbs, only 1,726 remain (approximately 700 of which are verbs with the negation modifier dé, which tend to not have conjugation tables in wiktionary since the root verb already has them) and it looks like, with a few exceptions, these are ones that do not have conjugation tables in wiktionary itself so these are correct to not have them in the JSON. I think that takes care of the vast majority of verbs that were missing inflection arrays.

**Comment by xxyzz** [comment]
Close as resolved, please open new issue or reopen this issue if you find other pages missing conjugation table data.
