### ISSUE TITLE
Incorrect parsing in some examples fields

### ISSUE THREAD

**Issue by rgossiaux** [tatuylonen/wiktextract#99]
I'm going to group together a couple different issues with the examples here so as not to spam. I'm referring to the French sections in all cases.

https://kaikki.org/dictionary/All%20languages%20combined/meaning/q/qu/quoi.html

```
      "examples": [
        {
          "english": "#:: Is there aught to do in England? No, there is not.",
          "text": "Y'a quoi à faire en Angleterre? Il n’y a pas de quoi."
        }
      ],
```

Here the `#::` markup made its way into the English field. Similarly for https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/co/cornet.html the `#*::` markup shows up.

---

https://kaikki.org/dictionary/All%20languages%20combined/meaning/f/fa/faire.html
 ```
"examples": [
        {
          "text": "Qu'est-ce que tu fais ? ― What are you doing?"
        },
        {
          "text": "Faire la vaisselle. ― To do the washing-up."
        },
        {
          "text": "Fais pas ça. ― Don't do that."
        }
      ],
```

Here the English translation isn't parsed correctly into a separate "english" field. The raw markup in the page has templates like `#: {{ux|fr|Qu'est-ce que tu '''fais''' ?|t=What are you '''doing'''?|inline=1}}` so I presume at some level it's possible to distinguish the example from the translation.

Another example at https://kaikki.org/dictionary/All%20languages%20combined/meaning/f/fr/fromage.html -- I mention this because the wiktionary template is slightly different here: `#: {{uxi|fr|fromage râpé|grated cheese}}`

https://kaikki.org/dictionary/All%20languages%20combined/meaning/a/ab/ablation.html -- this time it's from a quotation template; the relevant bit: 
``` 
passage={{...}} se contentant d'annoncer que l''''ablation''' des nouvelles permettra de voguer vers «la production d'émissions culturelles et de divertissement de qualité».|translation=merely announcing that the elimination of news programming [on tv channel [[w:TQS|TQS]]] will allow it to focus on "the production of quality entertainment and cultural programming"}} 
```

https://kaikki.org/dictionary/All%20languages%20combined/meaning/a/ac/accepter.html -- In this case the Wiktionary user wrote this didn't use an inline template and just wrote directly `#: ''je vais accepter votre offre'' - I'm going to accept your offer`

https://kaikki.org/dictionary/All%20languages%20combined/meaning/l/lu/lui.html -- Interestingly the first example ("I was living with him") is not parsed correctly, but the others are. This one is not an inline template, but rather a more standard two-line template: `#: {{ux|fr|J'habitais avec '''lui'''.|I was living with '''him'''.}}`

https://kaikki.org/dictionary/All%20languages%20combined/meaning/A/AD/ADN.html -- here someone has improvised their own markup again in Wiktionary: `#: ''La police a recours à l'analyse '''ADN''' pour identifier les criminels.'' (Police resort to DNA analysis in order to identify criminals.)` 

---

When translations are missing for examples, the autogenerated `(please add an English translation of this usage example)` text may get parsed as an English translation: https://kaikki.org/dictionary/All%20languages%20combined/meaning/b/bi/bitter.html 
```
      "examples": [
        {
          "english": "(please add an English translation of this usage example)",
          "text": "J’ai rien bitté au cours."
        }
      ],
```

The markup here is `#: {{ux|fr|J’ai rien '''bitté''' au cours.}}`

---

Unfortunately a large number of the example fields suffer from one or another of these issues, which makes it hard to work with right now.

**Comment by tatuylonen** [comment]
Thanks for the excellent bug report!

I think I fixed all of these cases, but haven't done extensive testing (I tested that each worked correctly after fixing it).  The changes should be reflected on https://kaikki.org tomorrow, unless something goes wrong with my overnight update.  It would be good if you can check that all have been fixed after the update.

Please let me know if you notice other issues!  The examples are quite a mess, and there are a lot of special cases.  I suspect there are still more cases that I don't handle yet.  Luckily these were fairly easy to fix.

**Comment by tatuylonen** [comment]
I also added a "type" field to usage examples.  Its value can currently be "example" or "quotation", or it can be missing if the type could not be determined.

**Comment by rgossiaux** [comment]
Incredible, thank you so much! I'll take another look over the weekend with the updated data.

**Comment by rgossiaux** [comment]
I got a chance now to look through the data again. Qualitatively it's a huge improvement, most of the examples look good now--thanks! I did still see a few edge cases:

* Looks like the quote template will add `(please add an English translation of this quote)`, eg https://kaikki.org/dictionary/All%20languages%20combined/meaning/r/ro/round.html. I also saw in https://kaikki.org/dictionary/All%20languages%20combined/meaning/s/se/seconde.html that this part didn't get split off into the "english" section like it does for other examples, even though I didn't see anything weird on the Wiktionary page.
* One of the examples in https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/co/condition.html doesn't have the English parsed -- looks like the Wiktionary page has `#: ''Le couple se contentait de soirées entre amis de conditions diverses.'' &mdash; The couple was content with partying with friends from all walks of life.` so I'm guessing it's the `&mdash;` markup
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/t/ta/tant%20pis.html I won't speculate on the cause here.
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/co/couleur.html -- There are extra commas in the quote that were added at the end of each line
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/n/na/natal.html -- noticed that the source markup here is unusual again: `#: {{l|fr|ville}} [[natale]]&nbsp;— ''home town''`
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/p/po/pot.html -- the French examples here have some English annotation at the beginning
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/h/ha/hard.html -- the ref fields have a stray #* at the end, also spotted here: https://kaikki.org/dictionary/All%20languages%20combined/meaning/m/me/mer.html
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/m/ma/masturbation.html -- the quote here wasn't parsed correctly

I found these by skimming through a sample of 1000 entries and skimming through their example fields. Most of them did look correct.

**Comment by tatuylonen** [comment]
Thank you.  These reports have already led to discovering and fixing a simple but very deep bug in wikitextprocessor in handling whitespace in #if and related parser functions.  That probably had subtle impacts in a lot of places.  I'm still working on the last of the issues you reported.

**Comment by tatuylonen** [comment]
I think I've fixed all of the new issues you reported. I started the overnight regeneration run, and unless something goes wrong, the changes should be visible on https://kaikki.org by noon European time tomorrow (Tuesday).  (Given some of the changes were way down in https://github.com/tatuylonen/wikitextprocessor, there is definitely a risk of the run failing.  The script also seems to be updating to a new Wiktionary dump.)

Please let me know if you notice any additional problems or if it turns out some of these were not fixed.  (BTW, including some text of the example or word sense helps, as then I can easily find the exact example referenced.)

**Comment by rgossiaux** [comment]
Ok, took another pass through with the latest data, here are the issues I found. They're all relatively minor and a few look like one-offs, but I'm just listing everything for reference:

* https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/ca/canon.html -- This example: `"text": "Cette nouvelle coupe de cheveux te va trop bien, t'es canon! - This new hair really suits you, you're hot!",`. It looks like the source page was using a template incorrectly (it had `#: {{uxi|fr|Cette nouvelle coupe de cheveux te va trop bien, t'es '''canon''' ! - This new hair really suits you, you're hot!}}` ) so to me this is more a problem with the source page (I went ahead and fixed it) but I thought I'd mention it anyway. Same thing here: https://kaikki.org/dictionary/All%20languages%20combined/meaning/p/pi/pis.html -- `"text": "\"Je suis habituée, protesta-t-elle. Pis j'ai pas besoin d'un père pour me faire la morale.\" — I'm used to it, she protested. And I don't need a father to lecture me",`
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/i/in/ineffable.html -- The ref was not parsed properly out of the example starting `1837 Louis Viardot, L’Ingénieux Hidalgo`. Ditto with https://kaikki.org/dictionary/All%20languages%20combined/meaning/c/ce/ce.html -- the example with `Cest un roc !`
* Sticking with the "ce" example above, it should actually say `C'est un roc !`. It looks like the ' are getting stripped here since on Wiktionary the c was bolded: `'''C''''est un roc !`
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/%C3%A0/%C3%A0/%C3%A0.html -- The ref field for one quote begins `(Can we date this quote?)` which is added by a template
* https://kaikki.org/dictionary/All%20languages%20combined/meaning/l/le/lez.html -- This example: `"Saint-André-lez-Lille est une ville proche de Lille.\nSaint-André-lez-Lille is a town near Lille."` On Wiktionary the second line has an additional level of indentation from the first. A similar thing happens https://kaikki.org/dictionary/All%20languages%20combined/meaning/t/te/tempe.html -- the example starting `1829, Victor Hugo, Le Dernier Jour d’un condamné\n` (which is also a ref that wasn't parsed). Another example: https://kaikki.org/dictionary/All%20languages%20combined/meaning/v/vi/violon.html -- the example beginning `Sur le toit de la maison, nous jouons du violon.` One more https://kaikki.org/dictionary/All%20languages%20combined/meaning/o/on/on.html -- the `2003, Natasha St. Pier` example (here too it's missing the ref)

Overall though it's still a big improvement even from yesterday, so thanks for all the work you're doing. Almost all of the examples look correct now, and given how unstructured and chaotic the source can be I don't expect wiktextract to be perfectly accurate.

**Comment by tatuylonen** [comment]
I fixed the first two bullet points (I think it is good to have generic code for these cases too).  The "ce" example goes deep: wikitextprocessor handles the '''C'''est construction incorrectly.  I'll continue from there next week.
